"""empty message

Revision ID: 6a86a524354a
Revises: f34697d5fa14
Create Date: 2025-04-20 01:59:04.923118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '6a86a524354a'
down_revision: Union[str, None] = 'f34697d5fa14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_messages_ticket_id_tickets', 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('fk_messages_ticket_id_tickets'), 'messages', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tickets', 'status_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('fk_tickets_status_id_ticket_statuses', 'tickets', type_='foreignkey')
    op.drop_constraint('fk_tickets_user_id_users', 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tickets_user_id_users'), 'tickets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_tickets_status_id_ticket_statuses'), 'tickets', 'ticket_statuses', ['status_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tickets_status_id_ticket_statuses'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('fk_tickets_user_id_users'), 'tickets', type_='foreignkey')
    op.create_foreign_key('fk_tickets_user_id_users', 'tickets', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_tickets_status_id_ticket_statuses', 'tickets', 'ticket_statuses', ['status_id'], ['id'])
    op.alter_column('tickets', 'status_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('fk_messages_ticket_id_tickets'), 'messages', type_='foreignkey')
    op.create_foreign_key('fk_messages_ticket_id_tickets', 'messages', 'tickets', ['ticket_id'], ['id'])
    # ### end Alembic commands ###
